remote_theme: mikearnaldi/just-the-docs

# Enable or disable the site search
search_enabled: false

# Aux links for the upper right navigation
aux_links:
'@effect/docgen on GitHub':
  - 'https://github.com/effect-ts/docgen'